// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd7W0yrJZqr6nEiy4K9T5WZehAaFKB13E',
    appId: '1:827307779331:web:c9daeb83d851b8988a7536',
    messagingSenderId: '827307779331',
    projectId: 'ctse-lab-activity',
    authDomain: 'ctse-lab-activity.firebaseapp.com',
    storageBucket: 'ctse-lab-activity.appspot.com',
    measurementId: 'G-3X2T4QDMQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcdXvdKl3uoB9wQpM84imqAHMlEQhExCM',
    appId: '1:827307779331:android:fefb7607da8597ed8a7536',
    messagingSenderId: '827307779331',
    projectId: 'ctse-lab-activity',
    storageBucket: 'ctse-lab-activity.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFw4PqbomFDuevNEwRIk6tL6FCzR1ukho',
    appId: '1:827307779331:ios:b4ea15a4a0070e4e8a7536',
    messagingSenderId: '827307779331',
    projectId: 'ctse-lab-activity',
    storageBucket: 'ctse-lab-activity.appspot.com',
    iosClientId: '827307779331-e6h473br9hi8jg6i8thmqbvvrtu9222n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseLabActivity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFw4PqbomFDuevNEwRIk6tL6FCzR1ukho',
    appId: '1:827307779331:ios:b4ea15a4a0070e4e8a7536',
    messagingSenderId: '827307779331',
    projectId: 'ctse-lab-activity',
    storageBucket: 'ctse-lab-activity.appspot.com',
    iosClientId: '827307779331-e6h473br9hi8jg6i8thmqbvvrtu9222n.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctseLabActivity',
  );
}
